// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drl_messages.proto

#ifndef PROTOBUF_drl_5fmessages_2eproto__INCLUDED
#define PROTOBUF_drl_5fmessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace DRL_MESSAGES {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_drl_5fmessages_2eproto();
void protobuf_AssignDesc_drl_5fmessages_2eproto();
void protobuf_ShutdownFile_drl_5fmessages_2eproto();

class drl_unimessage;
class drl_unimessage_Action;
class drl_unimessage_Dimension;
class drl_unimessage_Dimension_Component;
class drl_unimessage_GeneralStatePart;
class drl_unimessage_RLstate;
class drl_unimessage_RewardTerminal;

enum drl_unimessage_Type {
  drl_unimessage_Type_STATEPART = 1,
  drl_unimessage_Type_CONTROLACTION = 2,
  drl_unimessage_Type_RLSTATE = 3,
  drl_unimessage_Type_MESSTR = 4,
  drl_unimessage_Type_DIMENSION = 5,
  drl_unimessage_Type_REWARDTERMINAL = 6
};
bool drl_unimessage_Type_IsValid(int value);
const drl_unimessage_Type drl_unimessage_Type_Type_MIN = drl_unimessage_Type_STATEPART;
const drl_unimessage_Type drl_unimessage_Type_Type_MAX = drl_unimessage_Type_REWARDTERMINAL;
const int drl_unimessage_Type_Type_ARRAYSIZE = drl_unimessage_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* drl_unimessage_Type_descriptor();
inline const ::std::string& drl_unimessage_Type_Name(drl_unimessage_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    drl_unimessage_Type_descriptor(), value);
}
inline bool drl_unimessage_Type_Parse(
    const ::std::string& name, drl_unimessage_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<drl_unimessage_Type>(
    drl_unimessage_Type_descriptor(), name, value);
}
// ===================================================================

class drl_unimessage_GeneralStatePart : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DRL_MESSAGES.drl_unimessage.GeneralStatePart) */ {
 public:
  drl_unimessage_GeneralStatePart();
  virtual ~drl_unimessage_GeneralStatePart();

  drl_unimessage_GeneralStatePart(const drl_unimessage_GeneralStatePart& from);

  inline drl_unimessage_GeneralStatePart& operator=(const drl_unimessage_GeneralStatePart& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const drl_unimessage_GeneralStatePart& default_instance();

  void Swap(drl_unimessage_GeneralStatePart* other);

  // implements Message ----------------------------------------------

  inline drl_unimessage_GeneralStatePart* New() const { return New(NULL); }

  drl_unimessage_GeneralStatePart* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const drl_unimessage_GeneralStatePart& from);
  void MergeFrom(const drl_unimessage_GeneralStatePart& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(drl_unimessage_GeneralStatePart* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float state = 1;
  int state_size() const;
  void clear_state();
  static const int kStateFieldNumber = 1;
  float state(int index) const;
  void set_state(int index, float value);
  void add_state(float value);
  const ::google::protobuf::RepeatedField< float >&
      state() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_state();

  // repeated float first_derivative = 2;
  int first_derivative_size() const;
  void clear_first_derivative();
  static const int kFirstDerivativeFieldNumber = 2;
  float first_derivative(int index) const;
  void set_first_derivative(int index, float value);
  void add_first_derivative(float value);
  const ::google::protobuf::RepeatedField< float >&
      first_derivative() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_first_derivative();

  // repeated float second_derivative = 3;
  int second_derivative_size() const;
  void clear_second_derivative();
  static const int kSecondDerivativeFieldNumber = 3;
  float second_derivative(int index) const;
  void set_second_derivative(int index, float value);
  void add_second_derivative(float value);
  const ::google::protobuf::RepeatedField< float >&
      second_derivative() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_second_derivative();

  // repeated float third_deriavtive = 4;
  int third_deriavtive_size() const;
  void clear_third_deriavtive();
  static const int kThirdDeriavtiveFieldNumber = 4;
  float third_deriavtive(int index) const;
  void set_third_deriavtive(int index, float value);
  void add_third_deriavtive(float value);
  const ::google::protobuf::RepeatedField< float >&
      third_deriavtive() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_third_deriavtive();

  // @@protoc_insertion_point(class_scope:DRL_MESSAGES.drl_unimessage.GeneralStatePart)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > state_;
  ::google::protobuf::RepeatedField< float > first_derivative_;
  ::google::protobuf::RepeatedField< float > second_derivative_;
  ::google::protobuf::RepeatedField< float > third_deriavtive_;
  friend void  protobuf_AddDesc_drl_5fmessages_2eproto();
  friend void protobuf_AssignDesc_drl_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_drl_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static drl_unimessage_GeneralStatePart* default_instance_;
};
// -------------------------------------------------------------------

class drl_unimessage_Action : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DRL_MESSAGES.drl_unimessage.Action) */ {
 public:
  drl_unimessage_Action();
  virtual ~drl_unimessage_Action();

  drl_unimessage_Action(const drl_unimessage_Action& from);

  inline drl_unimessage_Action& operator=(const drl_unimessage_Action& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const drl_unimessage_Action& default_instance();

  void Swap(drl_unimessage_Action* other);

  // implements Message ----------------------------------------------

  inline drl_unimessage_Action* New() const { return New(NULL); }

  drl_unimessage_Action* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const drl_unimessage_Action& from);
  void MergeFrom(const drl_unimessage_Action& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(drl_unimessage_Action* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float actions = 1;
  int actions_size() const;
  void clear_actions();
  static const int kActionsFieldNumber = 1;
  float actions(int index) const;
  void set_actions(int index, float value);
  void add_actions(float value);
  const ::google::protobuf::RepeatedField< float >&
      actions() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_actions();

  // @@protoc_insertion_point(class_scope:DRL_MESSAGES.drl_unimessage.Action)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > actions_;
  friend void  protobuf_AddDesc_drl_5fmessages_2eproto();
  friend void protobuf_AssignDesc_drl_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_drl_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static drl_unimessage_Action* default_instance_;
};
// -------------------------------------------------------------------

class drl_unimessage_RLstate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DRL_MESSAGES.drl_unimessage.RLstate) */ {
 public:
  drl_unimessage_RLstate();
  virtual ~drl_unimessage_RLstate();

  drl_unimessage_RLstate(const drl_unimessage_RLstate& from);

  inline drl_unimessage_RLstate& operator=(const drl_unimessage_RLstate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const drl_unimessage_RLstate& default_instance();

  void Swap(drl_unimessage_RLstate* other);

  // implements Message ----------------------------------------------

  inline drl_unimessage_RLstate* New() const { return New(NULL); }

  drl_unimessage_RLstate* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const drl_unimessage_RLstate& from);
  void MergeFrom(const drl_unimessage_RLstate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(drl_unimessage_RLstate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sequence_index = 1;
  bool has_sequence_index() const;
  void clear_sequence_index();
  static const int kSequenceIndexFieldNumber = 1;
  ::google::protobuf::int32 sequence_index() const;
  void set_sequence_index(::google::protobuf::int32 value);

  // repeated float state = 2;
  int state_size() const;
  void clear_state();
  static const int kStateFieldNumber = 2;
  float state(int index) const;
  void set_state(int index, float value);
  void add_state(float value);
  const ::google::protobuf::RepeatedField< float >&
      state() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_state();

  // repeated float action = 3;
  int action_size() const;
  void clear_action();
  static const int kActionFieldNumber = 3;
  float action(int index) const;
  void set_action(int index, float value);
  void add_action(float value);
  const ::google::protobuf::RepeatedField< float >&
      action() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_action();

  // optional float reward = 4;
  bool has_reward() const;
  void clear_reward();
  static const int kRewardFieldNumber = 4;
  float reward() const;
  void set_reward(float value);

  // repeated .DRL_MESSAGES.drl_unimessage.GeneralStatePart observation = 5;
  int observation_size() const;
  void clear_observation();
  static const int kObservationFieldNumber = 5;
  const ::DRL_MESSAGES::drl_unimessage_GeneralStatePart& observation(int index) const;
  ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* mutable_observation(int index);
  ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* add_observation();
  ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_GeneralStatePart >*
      mutable_observation();
  const ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_GeneralStatePart >&
      observation() const;

  // @@protoc_insertion_point(class_scope:DRL_MESSAGES.drl_unimessage.RLstate)
 private:
  inline void set_has_sequence_index();
  inline void clear_has_sequence_index();
  inline void set_has_reward();
  inline void clear_has_reward();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > state_;
  ::google::protobuf::int32 sequence_index_;
  float reward_;
  ::google::protobuf::RepeatedField< float > action_;
  ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_GeneralStatePart > observation_;
  friend void  protobuf_AddDesc_drl_5fmessages_2eproto();
  friend void protobuf_AssignDesc_drl_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_drl_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static drl_unimessage_RLstate* default_instance_;
};
// -------------------------------------------------------------------

class drl_unimessage_Dimension_Component : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DRL_MESSAGES.drl_unimessage.Dimension.Component) */ {
 public:
  drl_unimessage_Dimension_Component();
  virtual ~drl_unimessage_Dimension_Component();

  drl_unimessage_Dimension_Component(const drl_unimessage_Dimension_Component& from);

  inline drl_unimessage_Dimension_Component& operator=(const drl_unimessage_Dimension_Component& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const drl_unimessage_Dimension_Component& default_instance();

  void Swap(drl_unimessage_Dimension_Component* other);

  // implements Message ----------------------------------------------

  inline drl_unimessage_Dimension_Component* New() const { return New(NULL); }

  drl_unimessage_Dimension_Component* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const drl_unimessage_Dimension_Component& from);
  void MergeFrom(const drl_unimessage_Dimension_Component& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(drl_unimessage_Dimension_Component* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string component_name = 1;
  bool has_component_name() const;
  void clear_component_name();
  static const int kComponentNameFieldNumber = 1;
  const ::std::string& component_name() const;
  void set_component_name(const ::std::string& value);
  void set_component_name(const char* value);
  void set_component_name(const char* value, size_t size);
  ::std::string* mutable_component_name();
  ::std::string* release_component_name();
  void set_allocated_component_name(::std::string* component_name);

  // repeated int32 component_dimension = 2;
  int component_dimension_size() const;
  void clear_component_dimension();
  static const int kComponentDimensionFieldNumber = 2;
  ::google::protobuf::int32 component_dimension(int index) const;
  void set_component_dimension(int index, ::google::protobuf::int32 value);
  void add_component_dimension(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      component_dimension() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_component_dimension();

  // @@protoc_insertion_point(class_scope:DRL_MESSAGES.drl_unimessage.Dimension.Component)
 private:
  inline void set_has_component_name();
  inline void clear_has_component_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr component_name_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > component_dimension_;
  friend void  protobuf_AddDesc_drl_5fmessages_2eproto();
  friend void protobuf_AssignDesc_drl_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_drl_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static drl_unimessage_Dimension_Component* default_instance_;
};
// -------------------------------------------------------------------

class drl_unimessage_Dimension : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DRL_MESSAGES.drl_unimessage.Dimension) */ {
 public:
  drl_unimessage_Dimension();
  virtual ~drl_unimessage_Dimension();

  drl_unimessage_Dimension(const drl_unimessage_Dimension& from);

  inline drl_unimessage_Dimension& operator=(const drl_unimessage_Dimension& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const drl_unimessage_Dimension& default_instance();

  void Swap(drl_unimessage_Dimension* other);

  // implements Message ----------------------------------------------

  inline drl_unimessage_Dimension* New() const { return New(NULL); }

  drl_unimessage_Dimension* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const drl_unimessage_Dimension& from);
  void MergeFrom(const drl_unimessage_Dimension& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(drl_unimessage_Dimension* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef drl_unimessage_Dimension_Component Component;

  // accessors -------------------------------------------------------

  // repeated .DRL_MESSAGES.drl_unimessage.Dimension.Component component = 1;
  int component_size() const;
  void clear_component();
  static const int kComponentFieldNumber = 1;
  const ::DRL_MESSAGES::drl_unimessage_Dimension_Component& component(int index) const;
  ::DRL_MESSAGES::drl_unimessage_Dimension_Component* mutable_component(int index);
  ::DRL_MESSAGES::drl_unimessage_Dimension_Component* add_component();
  ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_Dimension_Component >*
      mutable_component();
  const ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_Dimension_Component >&
      component() const;

  // @@protoc_insertion_point(class_scope:DRL_MESSAGES.drl_unimessage.Dimension)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_Dimension_Component > component_;
  friend void  protobuf_AddDesc_drl_5fmessages_2eproto();
  friend void protobuf_AssignDesc_drl_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_drl_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static drl_unimessage_Dimension* default_instance_;
};
// -------------------------------------------------------------------

class drl_unimessage_RewardTerminal : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DRL_MESSAGES.drl_unimessage.RewardTerminal) */ {
 public:
  drl_unimessage_RewardTerminal();
  virtual ~drl_unimessage_RewardTerminal();

  drl_unimessage_RewardTerminal(const drl_unimessage_RewardTerminal& from);

  inline drl_unimessage_RewardTerminal& operator=(const drl_unimessage_RewardTerminal& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const drl_unimessage_RewardTerminal& default_instance();

  void Swap(drl_unimessage_RewardTerminal* other);

  // implements Message ----------------------------------------------

  inline drl_unimessage_RewardTerminal* New() const { return New(NULL); }

  drl_unimessage_RewardTerminal* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const drl_unimessage_RewardTerminal& from);
  void MergeFrom(const drl_unimessage_RewardTerminal& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(drl_unimessage_RewardTerminal* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float reward = 1;
  bool has_reward() const;
  void clear_reward();
  static const int kRewardFieldNumber = 1;
  float reward() const;
  void set_reward(float value);

  // required int32 terminal = 2;
  bool has_terminal() const;
  void clear_terminal();
  static const int kTerminalFieldNumber = 2;
  ::google::protobuf::int32 terminal() const;
  void set_terminal(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DRL_MESSAGES.drl_unimessage.RewardTerminal)
 private:
  inline void set_has_reward();
  inline void clear_has_reward();
  inline void set_has_terminal();
  inline void clear_has_terminal();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float reward_;
  ::google::protobuf::int32 terminal_;
  friend void  protobuf_AddDesc_drl_5fmessages_2eproto();
  friend void protobuf_AssignDesc_drl_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_drl_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static drl_unimessage_RewardTerminal* default_instance_;
};
// -------------------------------------------------------------------

class drl_unimessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DRL_MESSAGES.drl_unimessage) */ {
 public:
  drl_unimessage();
  virtual ~drl_unimessage();

  drl_unimessage(const drl_unimessage& from);

  inline drl_unimessage& operator=(const drl_unimessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const drl_unimessage& default_instance();

  void Swap(drl_unimessage* other);

  // implements Message ----------------------------------------------

  inline drl_unimessage* New() const { return New(NULL); }

  drl_unimessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const drl_unimessage& from);
  void MergeFrom(const drl_unimessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(drl_unimessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef drl_unimessage_GeneralStatePart GeneralStatePart;
  typedef drl_unimessage_Action Action;
  typedef drl_unimessage_RLstate RLstate;
  typedef drl_unimessage_Dimension Dimension;
  typedef drl_unimessage_RewardTerminal RewardTerminal;

  typedef drl_unimessage_Type Type;
  static const Type STATEPART =
    drl_unimessage_Type_STATEPART;
  static const Type CONTROLACTION =
    drl_unimessage_Type_CONTROLACTION;
  static const Type RLSTATE =
    drl_unimessage_Type_RLSTATE;
  static const Type MESSTR =
    drl_unimessage_Type_MESSTR;
  static const Type DIMENSION =
    drl_unimessage_Type_DIMENSION;
  static const Type REWARDTERMINAL =
    drl_unimessage_Type_REWARDTERMINAL;
  static inline bool Type_IsValid(int value) {
    return drl_unimessage_Type_IsValid(value);
  }
  static const Type Type_MIN =
    drl_unimessage_Type_Type_MIN;
  static const Type Type_MAX =
    drl_unimessage_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    drl_unimessage_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return drl_unimessage_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return drl_unimessage_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return drl_unimessage_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .DRL_MESSAGES.drl_unimessage.Type type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::DRL_MESSAGES::drl_unimessage_Type type() const;
  void set_type(::DRL_MESSAGES::drl_unimessage_Type value);

  // required int32 time_index = 2;
  bool has_time_index() const;
  void clear_time_index();
  static const int kTimeIndexFieldNumber = 2;
  ::google::protobuf::int32 time_index() const;
  void set_time_index(::google::protobuf::int32 value);

  // optional string name = 3;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .DRL_MESSAGES.drl_unimessage.GeneralStatePart statepart = 4;
  bool has_statepart() const;
  void clear_statepart();
  static const int kStatepartFieldNumber = 4;
  const ::DRL_MESSAGES::drl_unimessage_GeneralStatePart& statepart() const;
  ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* mutable_statepart();
  ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* release_statepart();
  void set_allocated_statepart(::DRL_MESSAGES::drl_unimessage_GeneralStatePart* statepart);

  // optional .DRL_MESSAGES.drl_unimessage.Action action = 5;
  bool has_action() const;
  void clear_action();
  static const int kActionFieldNumber = 5;
  const ::DRL_MESSAGES::drl_unimessage_Action& action() const;
  ::DRL_MESSAGES::drl_unimessage_Action* mutable_action();
  ::DRL_MESSAGES::drl_unimessage_Action* release_action();
  void set_allocated_action(::DRL_MESSAGES::drl_unimessage_Action* action);

  // optional .DRL_MESSAGES.drl_unimessage.RLstate rlstate = 6;
  bool has_rlstate() const;
  void clear_rlstate();
  static const int kRlstateFieldNumber = 6;
  const ::DRL_MESSAGES::drl_unimessage_RLstate& rlstate() const;
  ::DRL_MESSAGES::drl_unimessage_RLstate* mutable_rlstate();
  ::DRL_MESSAGES::drl_unimessage_RLstate* release_rlstate();
  void set_allocated_rlstate(::DRL_MESSAGES::drl_unimessage_RLstate* rlstate);

  // optional string msgstr = 7;
  bool has_msgstr() const;
  void clear_msgstr();
  static const int kMsgstrFieldNumber = 7;
  const ::std::string& msgstr() const;
  void set_msgstr(const ::std::string& value);
  void set_msgstr(const char* value);
  void set_msgstr(const char* value, size_t size);
  ::std::string* mutable_msgstr();
  ::std::string* release_msgstr();
  void set_allocated_msgstr(::std::string* msgstr);

  // optional .DRL_MESSAGES.drl_unimessage.Dimension dimension = 8;
  bool has_dimension() const;
  void clear_dimension();
  static const int kDimensionFieldNumber = 8;
  const ::DRL_MESSAGES::drl_unimessage_Dimension& dimension() const;
  ::DRL_MESSAGES::drl_unimessage_Dimension* mutable_dimension();
  ::DRL_MESSAGES::drl_unimessage_Dimension* release_dimension();
  void set_allocated_dimension(::DRL_MESSAGES::drl_unimessage_Dimension* dimension);

  // optional .DRL_MESSAGES.drl_unimessage.RewardTerminal rwt = 9;
  bool has_rwt() const;
  void clear_rwt();
  static const int kRwtFieldNumber = 9;
  const ::DRL_MESSAGES::drl_unimessage_RewardTerminal& rwt() const;
  ::DRL_MESSAGES::drl_unimessage_RewardTerminal* mutable_rwt();
  ::DRL_MESSAGES::drl_unimessage_RewardTerminal* release_rwt();
  void set_allocated_rwt(::DRL_MESSAGES::drl_unimessage_RewardTerminal* rwt);

  // @@protoc_insertion_point(class_scope:DRL_MESSAGES.drl_unimessage)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_time_index();
  inline void clear_has_time_index();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_statepart();
  inline void clear_has_statepart();
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_rlstate();
  inline void clear_has_rlstate();
  inline void set_has_msgstr();
  inline void clear_has_msgstr();
  inline void set_has_dimension();
  inline void clear_has_dimension();
  inline void set_has_rwt();
  inline void clear_has_rwt();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  ::google::protobuf::int32 time_index_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* statepart_;
  ::DRL_MESSAGES::drl_unimessage_Action* action_;
  ::DRL_MESSAGES::drl_unimessage_RLstate* rlstate_;
  ::google::protobuf::internal::ArenaStringPtr msgstr_;
  ::DRL_MESSAGES::drl_unimessage_Dimension* dimension_;
  ::DRL_MESSAGES::drl_unimessage_RewardTerminal* rwt_;
  friend void  protobuf_AddDesc_drl_5fmessages_2eproto();
  friend void protobuf_AssignDesc_drl_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_drl_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static drl_unimessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// drl_unimessage_GeneralStatePart

// repeated float state = 1;
inline int drl_unimessage_GeneralStatePart::state_size() const {
  return state_.size();
}
inline void drl_unimessage_GeneralStatePart::clear_state() {
  state_.Clear();
}
inline float drl_unimessage_GeneralStatePart::state(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.GeneralStatePart.state)
  return state_.Get(index);
}
inline void drl_unimessage_GeneralStatePart::set_state(int index, float value) {
  state_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.GeneralStatePart.state)
}
inline void drl_unimessage_GeneralStatePart::add_state(float value) {
  state_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.GeneralStatePart.state)
}
inline const ::google::protobuf::RepeatedField< float >&
drl_unimessage_GeneralStatePart::state() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.state)
  return state_;
}
inline ::google::protobuf::RepeatedField< float >*
drl_unimessage_GeneralStatePart::mutable_state() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.state)
  return &state_;
}

// repeated float first_derivative = 2;
inline int drl_unimessage_GeneralStatePart::first_derivative_size() const {
  return first_derivative_.size();
}
inline void drl_unimessage_GeneralStatePart::clear_first_derivative() {
  first_derivative_.Clear();
}
inline float drl_unimessage_GeneralStatePart::first_derivative(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.GeneralStatePart.first_derivative)
  return first_derivative_.Get(index);
}
inline void drl_unimessage_GeneralStatePart::set_first_derivative(int index, float value) {
  first_derivative_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.GeneralStatePart.first_derivative)
}
inline void drl_unimessage_GeneralStatePart::add_first_derivative(float value) {
  first_derivative_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.GeneralStatePart.first_derivative)
}
inline const ::google::protobuf::RepeatedField< float >&
drl_unimessage_GeneralStatePart::first_derivative() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.first_derivative)
  return first_derivative_;
}
inline ::google::protobuf::RepeatedField< float >*
drl_unimessage_GeneralStatePart::mutable_first_derivative() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.first_derivative)
  return &first_derivative_;
}

// repeated float second_derivative = 3;
inline int drl_unimessage_GeneralStatePart::second_derivative_size() const {
  return second_derivative_.size();
}
inline void drl_unimessage_GeneralStatePart::clear_second_derivative() {
  second_derivative_.Clear();
}
inline float drl_unimessage_GeneralStatePart::second_derivative(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.GeneralStatePart.second_derivative)
  return second_derivative_.Get(index);
}
inline void drl_unimessage_GeneralStatePart::set_second_derivative(int index, float value) {
  second_derivative_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.GeneralStatePart.second_derivative)
}
inline void drl_unimessage_GeneralStatePart::add_second_derivative(float value) {
  second_derivative_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.GeneralStatePart.second_derivative)
}
inline const ::google::protobuf::RepeatedField< float >&
drl_unimessage_GeneralStatePart::second_derivative() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.second_derivative)
  return second_derivative_;
}
inline ::google::protobuf::RepeatedField< float >*
drl_unimessage_GeneralStatePart::mutable_second_derivative() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.second_derivative)
  return &second_derivative_;
}

// repeated float third_deriavtive = 4;
inline int drl_unimessage_GeneralStatePart::third_deriavtive_size() const {
  return third_deriavtive_.size();
}
inline void drl_unimessage_GeneralStatePart::clear_third_deriavtive() {
  third_deriavtive_.Clear();
}
inline float drl_unimessage_GeneralStatePart::third_deriavtive(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.GeneralStatePart.third_deriavtive)
  return third_deriavtive_.Get(index);
}
inline void drl_unimessage_GeneralStatePart::set_third_deriavtive(int index, float value) {
  third_deriavtive_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.GeneralStatePart.third_deriavtive)
}
inline void drl_unimessage_GeneralStatePart::add_third_deriavtive(float value) {
  third_deriavtive_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.GeneralStatePart.third_deriavtive)
}
inline const ::google::protobuf::RepeatedField< float >&
drl_unimessage_GeneralStatePart::third_deriavtive() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.third_deriavtive)
  return third_deriavtive_;
}
inline ::google::protobuf::RepeatedField< float >*
drl_unimessage_GeneralStatePart::mutable_third_deriavtive() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.GeneralStatePart.third_deriavtive)
  return &third_deriavtive_;
}

// -------------------------------------------------------------------

// drl_unimessage_Action

// repeated float actions = 1;
inline int drl_unimessage_Action::actions_size() const {
  return actions_.size();
}
inline void drl_unimessage_Action::clear_actions() {
  actions_.Clear();
}
inline float drl_unimessage_Action::actions(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.Action.actions)
  return actions_.Get(index);
}
inline void drl_unimessage_Action::set_actions(int index, float value) {
  actions_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.Action.actions)
}
inline void drl_unimessage_Action::add_actions(float value) {
  actions_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.Action.actions)
}
inline const ::google::protobuf::RepeatedField< float >&
drl_unimessage_Action::actions() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.Action.actions)
  return actions_;
}
inline ::google::protobuf::RepeatedField< float >*
drl_unimessage_Action::mutable_actions() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.Action.actions)
  return &actions_;
}

// -------------------------------------------------------------------

// drl_unimessage_RLstate

// optional int32 sequence_index = 1;
inline bool drl_unimessage_RLstate::has_sequence_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void drl_unimessage_RLstate::set_has_sequence_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void drl_unimessage_RLstate::clear_has_sequence_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void drl_unimessage_RLstate::clear_sequence_index() {
  sequence_index_ = 0;
  clear_has_sequence_index();
}
inline ::google::protobuf::int32 drl_unimessage_RLstate::sequence_index() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.RLstate.sequence_index)
  return sequence_index_;
}
inline void drl_unimessage_RLstate::set_sequence_index(::google::protobuf::int32 value) {
  set_has_sequence_index();
  sequence_index_ = value;
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.RLstate.sequence_index)
}

// repeated float state = 2;
inline int drl_unimessage_RLstate::state_size() const {
  return state_.size();
}
inline void drl_unimessage_RLstate::clear_state() {
  state_.Clear();
}
inline float drl_unimessage_RLstate::state(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.RLstate.state)
  return state_.Get(index);
}
inline void drl_unimessage_RLstate::set_state(int index, float value) {
  state_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.RLstate.state)
}
inline void drl_unimessage_RLstate::add_state(float value) {
  state_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.RLstate.state)
}
inline const ::google::protobuf::RepeatedField< float >&
drl_unimessage_RLstate::state() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.RLstate.state)
  return state_;
}
inline ::google::protobuf::RepeatedField< float >*
drl_unimessage_RLstate::mutable_state() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.RLstate.state)
  return &state_;
}

// repeated float action = 3;
inline int drl_unimessage_RLstate::action_size() const {
  return action_.size();
}
inline void drl_unimessage_RLstate::clear_action() {
  action_.Clear();
}
inline float drl_unimessage_RLstate::action(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.RLstate.action)
  return action_.Get(index);
}
inline void drl_unimessage_RLstate::set_action(int index, float value) {
  action_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.RLstate.action)
}
inline void drl_unimessage_RLstate::add_action(float value) {
  action_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.RLstate.action)
}
inline const ::google::protobuf::RepeatedField< float >&
drl_unimessage_RLstate::action() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.RLstate.action)
  return action_;
}
inline ::google::protobuf::RepeatedField< float >*
drl_unimessage_RLstate::mutable_action() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.RLstate.action)
  return &action_;
}

// optional float reward = 4;
inline bool drl_unimessage_RLstate::has_reward() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void drl_unimessage_RLstate::set_has_reward() {
  _has_bits_[0] |= 0x00000008u;
}
inline void drl_unimessage_RLstate::clear_has_reward() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void drl_unimessage_RLstate::clear_reward() {
  reward_ = 0;
  clear_has_reward();
}
inline float drl_unimessage_RLstate::reward() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.RLstate.reward)
  return reward_;
}
inline void drl_unimessage_RLstate::set_reward(float value) {
  set_has_reward();
  reward_ = value;
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.RLstate.reward)
}

// repeated .DRL_MESSAGES.drl_unimessage.GeneralStatePart observation = 5;
inline int drl_unimessage_RLstate::observation_size() const {
  return observation_.size();
}
inline void drl_unimessage_RLstate::clear_observation() {
  observation_.Clear();
}
inline const ::DRL_MESSAGES::drl_unimessage_GeneralStatePart& drl_unimessage_RLstate::observation(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.RLstate.observation)
  return observation_.Get(index);
}
inline ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* drl_unimessage_RLstate::mutable_observation(int index) {
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.RLstate.observation)
  return observation_.Mutable(index);
}
inline ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* drl_unimessage_RLstate::add_observation() {
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.RLstate.observation)
  return observation_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_GeneralStatePart >*
drl_unimessage_RLstate::mutable_observation() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.RLstate.observation)
  return &observation_;
}
inline const ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_GeneralStatePart >&
drl_unimessage_RLstate::observation() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.RLstate.observation)
  return observation_;
}

// -------------------------------------------------------------------

// drl_unimessage_Dimension_Component

// required string component_name = 1;
inline bool drl_unimessage_Dimension_Component::has_component_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void drl_unimessage_Dimension_Component::set_has_component_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void drl_unimessage_Dimension_Component::clear_has_component_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void drl_unimessage_Dimension_Component::clear_component_name() {
  component_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_component_name();
}
inline const ::std::string& drl_unimessage_Dimension_Component::component_name() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_name)
  return component_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void drl_unimessage_Dimension_Component::set_component_name(const ::std::string& value) {
  set_has_component_name();
  component_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_name)
}
inline void drl_unimessage_Dimension_Component::set_component_name(const char* value) {
  set_has_component_name();
  component_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_name)
}
inline void drl_unimessage_Dimension_Component::set_component_name(const char* value, size_t size) {
  set_has_component_name();
  component_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_name)
}
inline ::std::string* drl_unimessage_Dimension_Component::mutable_component_name() {
  set_has_component_name();
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_name)
  return component_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* drl_unimessage_Dimension_Component::release_component_name() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_name)
  clear_has_component_name();
  return component_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void drl_unimessage_Dimension_Component::set_allocated_component_name(::std::string* component_name) {
  if (component_name != NULL) {
    set_has_component_name();
  } else {
    clear_has_component_name();
  }
  component_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), component_name);
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_name)
}

// repeated int32 component_dimension = 2;
inline int drl_unimessage_Dimension_Component::component_dimension_size() const {
  return component_dimension_.size();
}
inline void drl_unimessage_Dimension_Component::clear_component_dimension() {
  component_dimension_.Clear();
}
inline ::google::protobuf::int32 drl_unimessage_Dimension_Component::component_dimension(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_dimension)
  return component_dimension_.Get(index);
}
inline void drl_unimessage_Dimension_Component::set_component_dimension(int index, ::google::protobuf::int32 value) {
  component_dimension_.Set(index, value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_dimension)
}
inline void drl_unimessage_Dimension_Component::add_component_dimension(::google::protobuf::int32 value) {
  component_dimension_.Add(value);
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_dimension)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
drl_unimessage_Dimension_Component::component_dimension() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_dimension)
  return component_dimension_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
drl_unimessage_Dimension_Component::mutable_component_dimension() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.Dimension.Component.component_dimension)
  return &component_dimension_;
}

// -------------------------------------------------------------------

// drl_unimessage_Dimension

// repeated .DRL_MESSAGES.drl_unimessage.Dimension.Component component = 1;
inline int drl_unimessage_Dimension::component_size() const {
  return component_.size();
}
inline void drl_unimessage_Dimension::clear_component() {
  component_.Clear();
}
inline const ::DRL_MESSAGES::drl_unimessage_Dimension_Component& drl_unimessage_Dimension::component(int index) const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.Dimension.component)
  return component_.Get(index);
}
inline ::DRL_MESSAGES::drl_unimessage_Dimension_Component* drl_unimessage_Dimension::mutable_component(int index) {
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.Dimension.component)
  return component_.Mutable(index);
}
inline ::DRL_MESSAGES::drl_unimessage_Dimension_Component* drl_unimessage_Dimension::add_component() {
  // @@protoc_insertion_point(field_add:DRL_MESSAGES.drl_unimessage.Dimension.component)
  return component_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_Dimension_Component >*
drl_unimessage_Dimension::mutable_component() {
  // @@protoc_insertion_point(field_mutable_list:DRL_MESSAGES.drl_unimessage.Dimension.component)
  return &component_;
}
inline const ::google::protobuf::RepeatedPtrField< ::DRL_MESSAGES::drl_unimessage_Dimension_Component >&
drl_unimessage_Dimension::component() const {
  // @@protoc_insertion_point(field_list:DRL_MESSAGES.drl_unimessage.Dimension.component)
  return component_;
}

// -------------------------------------------------------------------

// drl_unimessage_RewardTerminal

// required float reward = 1;
inline bool drl_unimessage_RewardTerminal::has_reward() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void drl_unimessage_RewardTerminal::set_has_reward() {
  _has_bits_[0] |= 0x00000001u;
}
inline void drl_unimessage_RewardTerminal::clear_has_reward() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void drl_unimessage_RewardTerminal::clear_reward() {
  reward_ = 0;
  clear_has_reward();
}
inline float drl_unimessage_RewardTerminal::reward() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.RewardTerminal.reward)
  return reward_;
}
inline void drl_unimessage_RewardTerminal::set_reward(float value) {
  set_has_reward();
  reward_ = value;
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.RewardTerminal.reward)
}

// required int32 terminal = 2;
inline bool drl_unimessage_RewardTerminal::has_terminal() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void drl_unimessage_RewardTerminal::set_has_terminal() {
  _has_bits_[0] |= 0x00000002u;
}
inline void drl_unimessage_RewardTerminal::clear_has_terminal() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void drl_unimessage_RewardTerminal::clear_terminal() {
  terminal_ = 0;
  clear_has_terminal();
}
inline ::google::protobuf::int32 drl_unimessage_RewardTerminal::terminal() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.RewardTerminal.terminal)
  return terminal_;
}
inline void drl_unimessage_RewardTerminal::set_terminal(::google::protobuf::int32 value) {
  set_has_terminal();
  terminal_ = value;
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.RewardTerminal.terminal)
}

// -------------------------------------------------------------------

// drl_unimessage

// required .DRL_MESSAGES.drl_unimessage.Type type = 1;
inline bool drl_unimessage::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void drl_unimessage::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void drl_unimessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void drl_unimessage::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::DRL_MESSAGES::drl_unimessage_Type drl_unimessage::type() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.type)
  return static_cast< ::DRL_MESSAGES::drl_unimessage_Type >(type_);
}
inline void drl_unimessage::set_type(::DRL_MESSAGES::drl_unimessage_Type value) {
  assert(::DRL_MESSAGES::drl_unimessage_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.type)
}

// required int32 time_index = 2;
inline bool drl_unimessage::has_time_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void drl_unimessage::set_has_time_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void drl_unimessage::clear_has_time_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void drl_unimessage::clear_time_index() {
  time_index_ = 0;
  clear_has_time_index();
}
inline ::google::protobuf::int32 drl_unimessage::time_index() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.time_index)
  return time_index_;
}
inline void drl_unimessage::set_time_index(::google::protobuf::int32 value) {
  set_has_time_index();
  time_index_ = value;
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.time_index)
}

// optional string name = 3;
inline bool drl_unimessage::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void drl_unimessage::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void drl_unimessage::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void drl_unimessage::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& drl_unimessage::name() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void drl_unimessage::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.name)
}
inline void drl_unimessage::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DRL_MESSAGES.drl_unimessage.name)
}
inline void drl_unimessage::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DRL_MESSAGES.drl_unimessage.name)
}
inline ::std::string* drl_unimessage::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* drl_unimessage::release_name() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void drl_unimessage::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.name)
}

// optional .DRL_MESSAGES.drl_unimessage.GeneralStatePart statepart = 4;
inline bool drl_unimessage::has_statepart() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void drl_unimessage::set_has_statepart() {
  _has_bits_[0] |= 0x00000008u;
}
inline void drl_unimessage::clear_has_statepart() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void drl_unimessage::clear_statepart() {
  if (statepart_ != NULL) statepart_->::DRL_MESSAGES::drl_unimessage_GeneralStatePart::Clear();
  clear_has_statepart();
}
inline const ::DRL_MESSAGES::drl_unimessage_GeneralStatePart& drl_unimessage::statepart() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.statepart)
  return statepart_ != NULL ? *statepart_ : *default_instance_->statepart_;
}
inline ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* drl_unimessage::mutable_statepart() {
  set_has_statepart();
  if (statepart_ == NULL) {
    statepart_ = new ::DRL_MESSAGES::drl_unimessage_GeneralStatePart;
  }
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.statepart)
  return statepart_;
}
inline ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* drl_unimessage::release_statepart() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.statepart)
  clear_has_statepart();
  ::DRL_MESSAGES::drl_unimessage_GeneralStatePart* temp = statepart_;
  statepart_ = NULL;
  return temp;
}
inline void drl_unimessage::set_allocated_statepart(::DRL_MESSAGES::drl_unimessage_GeneralStatePart* statepart) {
  delete statepart_;
  statepart_ = statepart;
  if (statepart) {
    set_has_statepart();
  } else {
    clear_has_statepart();
  }
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.statepart)
}

// optional .DRL_MESSAGES.drl_unimessage.Action action = 5;
inline bool drl_unimessage::has_action() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void drl_unimessage::set_has_action() {
  _has_bits_[0] |= 0x00000010u;
}
inline void drl_unimessage::clear_has_action() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void drl_unimessage::clear_action() {
  if (action_ != NULL) action_->::DRL_MESSAGES::drl_unimessage_Action::Clear();
  clear_has_action();
}
inline const ::DRL_MESSAGES::drl_unimessage_Action& drl_unimessage::action() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.action)
  return action_ != NULL ? *action_ : *default_instance_->action_;
}
inline ::DRL_MESSAGES::drl_unimessage_Action* drl_unimessage::mutable_action() {
  set_has_action();
  if (action_ == NULL) {
    action_ = new ::DRL_MESSAGES::drl_unimessage_Action;
  }
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.action)
  return action_;
}
inline ::DRL_MESSAGES::drl_unimessage_Action* drl_unimessage::release_action() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.action)
  clear_has_action();
  ::DRL_MESSAGES::drl_unimessage_Action* temp = action_;
  action_ = NULL;
  return temp;
}
inline void drl_unimessage::set_allocated_action(::DRL_MESSAGES::drl_unimessage_Action* action) {
  delete action_;
  action_ = action;
  if (action) {
    set_has_action();
  } else {
    clear_has_action();
  }
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.action)
}

// optional .DRL_MESSAGES.drl_unimessage.RLstate rlstate = 6;
inline bool drl_unimessage::has_rlstate() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void drl_unimessage::set_has_rlstate() {
  _has_bits_[0] |= 0x00000020u;
}
inline void drl_unimessage::clear_has_rlstate() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void drl_unimessage::clear_rlstate() {
  if (rlstate_ != NULL) rlstate_->::DRL_MESSAGES::drl_unimessage_RLstate::Clear();
  clear_has_rlstate();
}
inline const ::DRL_MESSAGES::drl_unimessage_RLstate& drl_unimessage::rlstate() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.rlstate)
  return rlstate_ != NULL ? *rlstate_ : *default_instance_->rlstate_;
}
inline ::DRL_MESSAGES::drl_unimessage_RLstate* drl_unimessage::mutable_rlstate() {
  set_has_rlstate();
  if (rlstate_ == NULL) {
    rlstate_ = new ::DRL_MESSAGES::drl_unimessage_RLstate;
  }
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.rlstate)
  return rlstate_;
}
inline ::DRL_MESSAGES::drl_unimessage_RLstate* drl_unimessage::release_rlstate() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.rlstate)
  clear_has_rlstate();
  ::DRL_MESSAGES::drl_unimessage_RLstate* temp = rlstate_;
  rlstate_ = NULL;
  return temp;
}
inline void drl_unimessage::set_allocated_rlstate(::DRL_MESSAGES::drl_unimessage_RLstate* rlstate) {
  delete rlstate_;
  rlstate_ = rlstate;
  if (rlstate) {
    set_has_rlstate();
  } else {
    clear_has_rlstate();
  }
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.rlstate)
}

// optional string msgstr = 7;
inline bool drl_unimessage::has_msgstr() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void drl_unimessage::set_has_msgstr() {
  _has_bits_[0] |= 0x00000040u;
}
inline void drl_unimessage::clear_has_msgstr() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void drl_unimessage::clear_msgstr() {
  msgstr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msgstr();
}
inline const ::std::string& drl_unimessage::msgstr() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.msgstr)
  return msgstr_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void drl_unimessage::set_msgstr(const ::std::string& value) {
  set_has_msgstr();
  msgstr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DRL_MESSAGES.drl_unimessage.msgstr)
}
inline void drl_unimessage::set_msgstr(const char* value) {
  set_has_msgstr();
  msgstr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DRL_MESSAGES.drl_unimessage.msgstr)
}
inline void drl_unimessage::set_msgstr(const char* value, size_t size) {
  set_has_msgstr();
  msgstr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DRL_MESSAGES.drl_unimessage.msgstr)
}
inline ::std::string* drl_unimessage::mutable_msgstr() {
  set_has_msgstr();
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.msgstr)
  return msgstr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* drl_unimessage::release_msgstr() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.msgstr)
  clear_has_msgstr();
  return msgstr_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void drl_unimessage::set_allocated_msgstr(::std::string* msgstr) {
  if (msgstr != NULL) {
    set_has_msgstr();
  } else {
    clear_has_msgstr();
  }
  msgstr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msgstr);
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.msgstr)
}

// optional .DRL_MESSAGES.drl_unimessage.Dimension dimension = 8;
inline bool drl_unimessage::has_dimension() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void drl_unimessage::set_has_dimension() {
  _has_bits_[0] |= 0x00000080u;
}
inline void drl_unimessage::clear_has_dimension() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void drl_unimessage::clear_dimension() {
  if (dimension_ != NULL) dimension_->::DRL_MESSAGES::drl_unimessage_Dimension::Clear();
  clear_has_dimension();
}
inline const ::DRL_MESSAGES::drl_unimessage_Dimension& drl_unimessage::dimension() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.dimension)
  return dimension_ != NULL ? *dimension_ : *default_instance_->dimension_;
}
inline ::DRL_MESSAGES::drl_unimessage_Dimension* drl_unimessage::mutable_dimension() {
  set_has_dimension();
  if (dimension_ == NULL) {
    dimension_ = new ::DRL_MESSAGES::drl_unimessage_Dimension;
  }
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.dimension)
  return dimension_;
}
inline ::DRL_MESSAGES::drl_unimessage_Dimension* drl_unimessage::release_dimension() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.dimension)
  clear_has_dimension();
  ::DRL_MESSAGES::drl_unimessage_Dimension* temp = dimension_;
  dimension_ = NULL;
  return temp;
}
inline void drl_unimessage::set_allocated_dimension(::DRL_MESSAGES::drl_unimessage_Dimension* dimension) {
  delete dimension_;
  dimension_ = dimension;
  if (dimension) {
    set_has_dimension();
  } else {
    clear_has_dimension();
  }
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.dimension)
}

// optional .DRL_MESSAGES.drl_unimessage.RewardTerminal rwt = 9;
inline bool drl_unimessage::has_rwt() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void drl_unimessage::set_has_rwt() {
  _has_bits_[0] |= 0x00000100u;
}
inline void drl_unimessage::clear_has_rwt() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void drl_unimessage::clear_rwt() {
  if (rwt_ != NULL) rwt_->::DRL_MESSAGES::drl_unimessage_RewardTerminal::Clear();
  clear_has_rwt();
}
inline const ::DRL_MESSAGES::drl_unimessage_RewardTerminal& drl_unimessage::rwt() const {
  // @@protoc_insertion_point(field_get:DRL_MESSAGES.drl_unimessage.rwt)
  return rwt_ != NULL ? *rwt_ : *default_instance_->rwt_;
}
inline ::DRL_MESSAGES::drl_unimessage_RewardTerminal* drl_unimessage::mutable_rwt() {
  set_has_rwt();
  if (rwt_ == NULL) {
    rwt_ = new ::DRL_MESSAGES::drl_unimessage_RewardTerminal;
  }
  // @@protoc_insertion_point(field_mutable:DRL_MESSAGES.drl_unimessage.rwt)
  return rwt_;
}
inline ::DRL_MESSAGES::drl_unimessage_RewardTerminal* drl_unimessage::release_rwt() {
  // @@protoc_insertion_point(field_release:DRL_MESSAGES.drl_unimessage.rwt)
  clear_has_rwt();
  ::DRL_MESSAGES::drl_unimessage_RewardTerminal* temp = rwt_;
  rwt_ = NULL;
  return temp;
}
inline void drl_unimessage::set_allocated_rwt(::DRL_MESSAGES::drl_unimessage_RewardTerminal* rwt) {
  delete rwt_;
  rwt_ = rwt;
  if (rwt) {
    set_has_rwt();
  } else {
    clear_has_rwt();
  }
  // @@protoc_insertion_point(field_set_allocated:DRL_MESSAGES.drl_unimessage.rwt)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DRL_MESSAGES

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::DRL_MESSAGES::drl_unimessage_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DRL_MESSAGES::drl_unimessage_Type>() {
  return ::DRL_MESSAGES::drl_unimessage_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_drl_5fmessages_2eproto__INCLUDED
