experiment: 
  type: experiment/online_learning
  runs: 10
  run_offset: 0
  trials: 10000
  steps: 0
  rate: 0
  test_interval: 10
  output: mpol_ddpg_4_density_based_data
  environment: 
    type: environment/modeled
    model: 
      type: model/dynamical
      control_step: 0.03
      integration_steps: 5
      dynamics: 
        type: dynamics/pendulum
    task: 
      type: task/pendulum/swingup
      timeout: 2.99
      randomization: 1
      sincos: 0
  agent: 
    type: agent/replay
    memory_size: 100000
    replay_steps: 64
    batch_size: 64
    observation_steps: 1000
    threads: 0
    policy: 
      type: mapping/policy/multi
      strategy: density_based
      sampler: 
        type: sampler/greedy
      bins: 10
      static_policy: 0
      r_distance_parameter: 0.005
      alpha: 0.75
      iroulette: 0.01
      minor_remove_bound: 0.25
      major_remove_bound: 0.75
      policy: 
        - 
          type: mapping/policy/post/noise
          sigma: [1]
          theta: [0.15]
          decay_rate: 0.9
          decay_min: 0.1
          output_min: experiment/environment/task/action_min
          output_max: experiment/environment/task/action_max
          policy: 
            type: mapping/policy/filtering
            observation_idx: [0, 1]
            action_idx: [0]
            policy: 
              type: mapping/policy/action
              sigma: 0
              decay_rate: 0
              decay_min: 0
              output_min: experiment/environment/task/action_min++[0]
              output_max: experiment/environment/task/action_max++[0]
              projector: 
                type: projector/pre/normalizing
                input_min: experiment/environment/task/observation_min
                input_max: experiment/environment/task/observation_max
                projector: 
                  type: projector/identity
              representation: 
                type: representation/parameterized/tensorflow
                interval: 10000
                inputs: experiment/environment/task/observation_dims
                targets: experiment/environment/task/action_dims
                file: pendulum_ddpg.pb
                input_layer: s_in
                output_layer: a_out/mul, q/BiasAdd
                output_target: q_target
                update_node: q_update
        - 
          type: mapping/policy/post/noise
          sigma: [1]
          theta: [0.15]
          decay_rate: 0.9
          decay_min: 0.1
          output_min: experiment/environment/task/action_min
          output_max: experiment/environment/task/action_max
          policy: 
            type: mapping/policy/filtering
            observation_idx: [0, 1]
            action_idx: [0]
            policy: 
              type: mapping/policy/action
              sigma: 0
              decay_rate: 0
              decay_min: 0
              output_min: experiment/environment/task/action_min++[0]
              output_max: experiment/environment/task/action_max++[0]
              projector: 
                type: projector/pre/normalizing
                input_min: experiment/environment/task/observation_min
                input_max: experiment/environment/task/observation_max
                projector: 
                  type: projector/identity
              representation: 
                type: representation/parameterized/tensorflow
                interval: 10000
                inputs: experiment/environment/task/observation_dims
                targets: experiment/environment/task/action_dims
                file: pendulum_ddpg.pb
                input_layer: s_in
                output_layer: a_out/mul, q/BiasAdd
                output_target: q_target
                update_node: q_update
        - 
          type: mapping/policy/post/noise
          sigma: [1]
          theta: [0.15]
          decay_rate: 0.9
          decay_min: 0.1
          output_min: experiment/environment/task/action_min
          output_max: experiment/environment/task/action_max
          policy: 
            type: mapping/policy/filtering
            observation_idx: [0, 1]
            action_idx: [0]
            policy: 
              type: mapping/policy/action
              sigma: 0
              decay_rate: 0
              decay_min: 0
              output_min: experiment/environment/task/action_min++[0]
              output_max: experiment/environment/task/action_max++[0]
              projector: 
                type: projector/pre/normalizing
                input_min: experiment/environment/task/observation_min
                input_max: experiment/environment/task/observation_max
                projector: 
                  type: projector/identity
              representation: 
                type: representation/parameterized/tensorflow
                interval: 10000
                inputs: experiment/environment/task/observation_dims
                targets: experiment/environment/task/action_dims
                file: pendulum_ddpg.pb
                input_layer: s_in
                output_layer: a_out/mul, q/BiasAdd
                output_target: q_target
                update_node: q_update
        - 
          type: mapping/policy/post/noise
          sigma: [1]
          theta: [0.15]
          decay_rate: 0.9
          decay_min: 0.1
          output_min: experiment/environment/task/action_min
          output_max: experiment/environment/task/action_max
          policy: 
            type: mapping/policy/filtering
            observation_idx: [0, 1]
            action_idx: [0]
            policy: 
              type: mapping/policy/action
              sigma: 0
              decay_rate: 0
              decay_min: 0
              output_min: experiment/environment/task/action_min++[0]
              output_max: experiment/environment/task/action_max++[0]
              projector: 
                type: projector/pre/normalizing
                input_min: experiment/environment/task/observation_min
                input_max: experiment/environment/task/observation_max
                projector: 
                  type: projector/identity
              representation: 
                type: representation/parameterized/tensorflow
                interval: 10000
                inputs: experiment/environment/task/observation_dims
                targets: experiment/environment/task/action_dims
                file: pendulum_ddpg.pb
                input_layer: s_in
                output_layer: a_out/mul, q/BiasAdd
                output_target: q_target
                update_node: q_update
      value: 
        - 
          type: mapping/represented
          projector: experiment/agent/policy/policy/0/policy/policy/projector
          representation: experiment/agent/policy/policy/0/policy/policy/representation
        - 
          type: mapping/represented
          projector: experiment/agent/policy/policy/1/policy/policy/projector
          representation: experiment/agent/policy/policy/1/policy/policy/representation
        - 
          type: mapping/represented
          projector: experiment/agent/policy/policy/2/policy/policy/projector
          representation: experiment/agent/policy/policy/1/policy/policy/representation
        - 
          type: mapping/represented
          projector: experiment/agent/policy/policy/2/policy/policy/projector
          representation: experiment/agent/policy/policy/1/policy/policy/representation
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max
    predictor: 
      type: predictor/multi
      predictor: 
        - 
          type: predictor/ddpg
          gamma: 0.99
          observation: s_in
          action: a_in
          value: q/BiasAdd
          target: q_target
          critic_update: q_update
          actor_update: a_update
          obs_projector: 
            type: projector/pre/normalizing
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/identity
          action_projector: 
            type: projector/identity
          representation: experiment/agent/policy/policy/0/policy/policy/representation
        - 
          type: predictor/ddpg
          gamma: 0.98
          observation: s_in
          action: a_in
          value: q/BiasAdd
          target: q_target
          critic_update: q_update
          actor_update: a_update
          obs_projector: 
            type: projector/pre/normalizing
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/identity
          action_projector: 
            type: projector/identity
          representation: experiment/agent/policy/policy/1/policy/policy/representation
        - 
          type: predictor/ddpg
          gamma: 0.97
          observation: s_in
          action: a_in
          value: q/BiasAdd
          target: q_target
          critic_update: q_update
          actor_update: a_update
          obs_projector: 
            type: projector/pre/normalizing
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/identity
          action_projector: 
            type: projector/identity
          representation: experiment/agent/policy/policy/1/policy/policy/representation
        - 
          type: predictor/ddpg
          gamma: 0.96
          observation: s_in
          action: a_in
          value: q/BiasAdd
          target: q_target
          critic_update: q_update
          actor_update: a_update
          obs_projector: 
            type: projector/pre/normalizing
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/identity
          action_projector: 
            type: projector/identity
          representation: experiment/agent/policy/policy/1/policy/policy/representation
  test_agent: 
    type: agent/fixed
    policy: 
      type: mapping/policy/multi
      strategy: experiment/agent/policy/strategy
      sampler: experiment/agent/policy/sampler
      bins: experiment/agent/policy/bins
      static_policy: experiment/agent/policy/static_policy
      r_distance_parameter: experiment/agent/policy/r_distance_parameter
      alpha: experiment/agent/policy/alpha
      iroulette: experiment/agent/policy/iroulette
      minor_remove_bound: experiment/agent/policy/minor_remove_bound
      major_remove_bound: experiment/agent/policy/major_remove_bound
      policy: 
        - 
          type: mapping/policy/filtering
          observation_idx: [0, 1]
          action_idx: [0]
          policy: 
            type: mapping/policy/action
            sigma: 0
            decay_rate: 1
            decay_min: 0
            output_min: experiment/agent/policy/policy/0/policy/policy/output_min
            output_max: experiment/agent/policy/policy/0/policy/policy/output_max
            projector: experiment/agent/policy/policy/0/policy/policy/projector
            representation: experiment/agent/policy/policy/0/policy/policy/representation
        - 
          type: mapping/policy/filtering
          observation_idx: [0, 1]
          action_idx: [0]
          policy: 
            type: mapping/policy/action
            sigma: 0
            decay_rate: 1
            decay_min: 0
            output_min: experiment/agent/policy/policy/1/policy/policy/output_min
            output_max: experiment/agent/policy/policy/1/policy/policy/output_max
            projector: experiment/agent/policy/policy/1/policy/policy/projector
            representation: experiment/agent/policy/policy/1/policy/policy/representation
        - 
          type: mapping/policy/filtering
          observation_idx: [0, 1]
          action_idx: [0]
          policy: 
            type: mapping/policy/action
            sigma: 0
            decay_rate: 1
            decay_min: 0
            output_min: experiment/agent/policy/policy/2/policy/policy/output_min
            output_max: experiment/agent/policy/policy/2/policy/policy/output_max
            projector: experiment/agent/policy/policy/2/policy/policy/projector
            representation: experiment/agent/policy/policy/2/policy/policy/representation
        - 
          type: mapping/policy/filtering
          observation_idx: [0, 1]
          action_idx: [0]
          policy: 
            type: mapping/policy/action
            sigma: 0
            decay_rate: 1
            decay_min: 0
            output_min: experiment/agent/policy/policy/3/policy/policy/output_min
            output_max: experiment/agent/policy/policy/3/policy/policy/output_max
            projector: experiment/agent/policy/policy/3/policy/policy/projector
            representation: experiment/agent/policy/policy/3/policy/policy/representation
      value: 
        - experiment/agent/policy/value/0
        - experiment/agent/policy/value/1
        - experiment/agent/policy/value/2
        - experiment/agent/policy/value/3
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max
  save_every: never
points: 4096
delay: 1
policy_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 0
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/0/policy/policy/projector
    representation: experiment/agent/policy/policy/0/policy/policy/representation
value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 1
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/0/policy/policy/projector
    representation: experiment/agent/policy/policy/0/policy/policy/representation
target_value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 1
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/0/policy/policy/projector
    representation: experiment/agent/policy/policy/0/policy/policy/representation/target
curve_visualization: 
  type: visualization/state
  input_dims: []
  input_min: [-4000]
  input_max: [0]
  memory: 256
  state: experiment/curve
