experiment: 
  type: experiment/online_learning
  runs: 1
  run_offset: 0
  trials: 1000
  steps: 0
  rate: 0
  test_interval: 10
  output: mpol_ddpg_3_density_based_data
  environment: 
    type: environment/modeled
    discrete_time: 1
    model: 
      type: model/dynamical
      control_step: 0.03
      integration_steps: 5
      dynamics: 
        type: dynamics/pendulum
    task: 
      type: task/pendulum/swingup
      timeout: 2.99
      randomization: 1
  agent: 
    type: agent/replay
    memory_size: 100000
    replay_steps: 64
    batch_size: 64
    observation_steps: 1000
    threads: 0
    policy: 
      type: mapping/policy/multi
      strategy: alg4stepsNew
      ensemble_center: none
      update_history: none
      percentile: 1
      select_by_distance: density
      score_postprocess: 0
      sampler: 
        type: sampler/greedy
      bins: 10
      static_policy: 0
      r_distance_parameter: 0.005
      alpha: 0.01
      iroulette: 0.3
      minor_remove_bound: 0.25
      major_remove_bound: 0.75
      policy: 
        - 
          type: mapping/policy/action
          sigma: [1]
          theta: [0.15]
          decay_rate: 1
          decay_min: 0
          renormalize: 1
          output_min: experiment/environment/task/action_min
          output_max: experiment/environment/task/action_max
          projector: 
            type: projector/pre/normalizing
            signed: 0
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/pre/geometric
              angles: [1, 0]
              normalized: 1
              projector: 
                type: projector/identity
          representation: 
            type: representation/parameterized/tensorflow
            interval: 100
            tau: 0.01
            file_suffix: my_policy_1
            file: ../cfg/network/4layer_tanh_ddpg.py ../../projector/projector/memory experiment/environment/task/action_dims
            input_layer: s_in, a_in
            output_layer: a_out/Tanh
            init_node: init
            update_node: update
        - 
          type: mapping/policy/action
          sigma: [1]
          theta: [0.15]
          decay_rate: 1
          decay_min: 0
          renormalize: 1
          output_min: experiment/environment/task/action_min
          output_max: experiment/environment/task/action_max
          projector: 
            type: projector/pre/normalizing
            signed: 0
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/pre/geometric
              angles: [1, 0]
              normalized: 1
              projector: 
                type: projector/identity
          representation: 
            type: representation/parameterized/tensorflow
            interval: 100
            tau: 0.01
            file_suffix: my_policy_1
            file: ../cfg/network/4layer_tanh_ddpg.py ../../projector/projector/memory experiment/environment/task/action_dims 0.001 0.001 "softmax" "linear" 100 50
            input_layer: s_in, a_in
            output_layer: a_out/Tanh
            init_node: init
            update_node: update
        - 
          type: mapping/policy/action
          sigma: [1]
          theta: [0.15]
          decay_rate: 1
          decay_min: 0
          renormalize: 1
          output_min: experiment/environment/task/action_min
          output_max: experiment/environment/task/action_max
          projector: 
            type: projector/pre/normalizing
            signed: 0
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/pre/geometric
              angles: [1, 0]
              normalized: 1
              projector: 
                type: projector/identity
          representation: 
            type: representation/parameterized/tensorflow
            interval: 100
            tau: 0.01
            file_suffix: my_policy_1
            file: ../cfg/network/4layer_tanh_ddpg.py ../../projector/projector/memory experiment/environment/task/action_dims
            input_layer: s_in, a_in
            output_layer: a_out/Tanh
            init_node: init
            update_node: update
      value: 
        - 
          type: mapping/represented
          projector: experiment/agent/policy/policy/0/projector
          representation: experiment/agent/policy/policy/0/representation
        - 
          type: mapping/represented
          projector: experiment/agent/policy/policy/1/projector
          representation: experiment/agent/policy/policy/1/representation
        - 
          type: mapping/represented
          projector: experiment/agent/policy/policy/2/projector
          representation: experiment/agent/policy/policy/2/representation
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max
    predictor: 
      type: predictor/multi
      predictor: 
        - 
          type: predictor/ddpg
          gamma: 0.98
          reward_scale: 1
          observation: s_in
          action: a_in
          value: q/BiasAdd
          target: target
          critic_update: update
          actor_update: a_update
          discretizer: 0
          obs_projector: experiment/agent/policy/policy/0/projector
          action_projector: 
            type: projector/pre/normalizing
            signed: 1
            input_min: experiment/environment/task/action_min
            input_max: experiment/environment/task/action_max
            projector: 
              type: projector/identity
          representation: experiment/agent/policy/policy/0/representation
        - 
          type: predictor/ddpg
          gamma: 0.99
          reward_scale: 0.01
          observation: s_in
          action: a_in
          value: q/BiasAdd
          target: target
          critic_update: update
          actor_update: a_update
          discretizer: 0
          obs_projector: experiment/agent/policy/policy/1/projector
          action_projector: 
            type: projector/pre/normalizing
            signed: 1
            input_min: experiment/environment/task/action_min
            input_max: experiment/environment/task/action_max
            projector: 
              type: projector/identity
          representation: experiment/agent/policy/policy/1/representation
        - 
          type: predictor/ddpg
          gamma: 0.99
          reward_scale: 0.01
          observation: s_in
          action: a_in
          value: q/BiasAdd
          target: target
          critic_update: update
          actor_update: a_update
          discretizer: 0
          obs_projector: experiment/agent/policy/policy/2/projector
          action_projector: 
            type: projector/pre/normalizing
            signed: 1
            input_min: experiment/environment/task/action_min
            input_max: experiment/environment/task/action_max
            projector: 
              type: projector/identity
          representation: experiment/agent/policy/policy/2/representation
  test_agent: 
    type: agent/fixed
    policy: 
      type: mapping/policy/multi
      strategy: experiment/agent/policy/strategy
      ensemble_center: experiment/agent/policy/ensemble_center
      update_history: experiment/agent/policy/update_history
      percentile: experiment/agent/policy/percentile
      select_by_distance: experiment/agent/policy/select_by_distance
      score_postprocess: experiment/agent/policy/score_postprocess
      sampler: experiment/agent/policy/sampler
      bins: experiment/agent/policy/bins
      static_policy: experiment/agent/policy/static_policy
      r_distance_parameter: experiment/agent/policy/r_distance_parameter
      alpha: experiment/agent/policy/alpha
      iroulette: experiment/agent/policy/iroulette
      minor_remove_bound: experiment/agent/policy/minor_remove_bound
      major_remove_bound: experiment/agent/policy/major_remove_bound
      policy: 
        - 
          type: mapping/policy/action
          sigma: []
          theta: []
          decay_rate: 1
          decay_min: 0
          renormalize: 1
          output_min: experiment/agent/policy/policy/0/output_min
          output_max: experiment/agent/policy/policy/0/output_max
          projector: experiment/agent/policy/policy/0/projector
          representation: experiment/agent/policy/policy/0/representation
        - 
          type: mapping/policy/action
          sigma: []
          theta: []
          decay_rate: 1
          decay_min: 0
          renormalize: 1
          output_min: experiment/agent/policy/policy/1/output_min
          output_max: experiment/agent/policy/policy/1/output_max
          projector: experiment/agent/policy/policy/1/projector
          representation: experiment/agent/policy/policy/1/representation
        - 
          type: mapping/policy/action
          sigma: []
          theta: []
          decay_rate: 1
          decay_min: 0
          renormalize: 1
          output_min: experiment/agent/policy/policy/2/output_min
          output_max: experiment/agent/policy/policy/2/output_max
          projector: experiment/agent/policy/policy/2/projector
          representation: experiment/agent/policy/policy/2/representation
      value: 
        - experiment/agent/policy/value/0
        - experiment/agent/policy/value/1
        - experiment/agent/policy/value/2
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max
  save_every: never
