experiment: 
  type: experiment/online_learning
  runs: 1
  run_offset: 0
  trials: 0
  steps: 0
  rate: 0
  test_interval: 10
  environment: 
    type: environment/modeled
    discrete_time: 1
    model: 
      type: model/dynamical
      control_step: 0.03
      integration_steps: 5
      dynamics: 
        type: dynamics/pendulum
    task: 
      type: task/pendulum/swingup
      timeout: 2.99
      randomization: 1
    exporter: 0
  agent: 
    type: agent/replay
    memory_size: 100000
    replay_steps: 256
    batch_size: 64
    observation_steps: 1000
    threads: 0
    policy: 
      type: mapping/policy/filtering
      observation_idx: [0, 1]
      action_idx: [1]
      policy: 
        type: mapping/policy/action
        sigma: [1]
        theta: [0.15]
        decay_rate: 1
        decay_min: 0
        renormalize: 1
        output_min: 0++experiment/environment/task/action_min
        output_max: 0++experiment/environment/task/action_max
        projector: 
          type: projector/pre/normalizing
          signed: 0
          input_min: experiment/environment/task/observation_min
          input_max: experiment/environment/task/observation_max
          projector: 
            type: projector/identity
        representation: 
          type: representation/parameterized/tensorflow
          interval: 10000
          file: ../cfg/network/4layer_tanh_ddpg.py experiment/environment/task/observation_dims experiment/environment/task/action_dims
          input_layer: s_in, a_in
          output_layer: q/BiasAdd, a_out/Tanh
          init_node: init
          update_node: update
    predictor: 
      type: predictor/ddpg
      importer: 0
      exporter: 0
      gamma: 0.99
      reward_scale: 1
      observation: s_in
      action: a_in
      value: q/BiasAdd
      target: target
      critic_update: update
      actor_update: a_update
      discretizer: 0
      obs_projector: 
        type: projector/pre/normalizing
        signed: 0
        input_min: experiment/environment/task/observation_min
        input_max: experiment/environment/task/observation_max
        projector: 
          type: projector/identity
      action_projector: 
        type: projector/pre/normalizing
        signed: 1
        input_min: experiment/environment/task/action_min
        input_max: experiment/environment/task/action_max
        projector: 
          type: projector/identity
      representation: experiment/agent/policy/policy/representation
  test_agent: 
    type: agent/fixed
    policy: 
      type: mapping/policy/filtering
      observation_idx: [0, 1]
      action_idx: [1]
      policy: 
        type: mapping/policy/action
        sigma: []
        theta: []
        decay_rate: 1
        decay_min: 0
        renormalize: 1
        output_min: experiment/agent/policy/policy/output_min
        output_max: experiment/agent/policy/policy/output_max
        projector: experiment/agent/policy/policy/projector
        representation: experiment/agent/policy/policy/representation
  save_every: never
points: 4096
delay: 1
policy_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 1
  points: points
  savepoints: 1048576
  delay: delay
  state: experiment/state
  action: 0
  mapping: experiment/test_agent/policy/policy
curve_visualization: 
  type: visualization/state
  input_dims: []
  input_min: [-4000]
  input_max: [0]
  memory: 256
  state: experiment/curve
