experiment: 
  type: experiment/online_learning
  runs: 10
  run_offset: 0
  trials: 10000
  steps: 0
  rate: 0
  test_interval: 10
  output: cartpole_mpol_1_replay_ddpg_tensorflow_data
  environment: 
    type: environment/modeled
    model: 
      type: model/dynamical
      control_step: 0.05
      integration_steps: 5
      dynamics: 
        type: dynamics/cart_pole
        end_stop: 1
    task: 
      type: task/cart_pole/swingup
      timeout: 9.99
      randomization: 1
      shaping: 0
      gamma: 1
      end_stop_penalty: 0
      action_penalty: 0
  agent: 
    type: agent/replay
    memory_size: 100000
    replay_steps: 64
    batch_size: 32
    observation_steps: 1000
    threads: 0
    policy: 
      type: mapping/policy/post/noise
      sigma: [1]
      theta: [0.15]
      decay_rate: 0.99
      decay_min: 0.1
      output_min: experiment/environment/task/action_min
      output_max: experiment/environment/task/action_max
      policy: 
        type: mapping/policy/filtering
        observation_idx: [0, 1, 2, 3]
        action_idx: [0]
        policy: 
          type: mapping/policy/action
          sigma: 0
          decay_rate: 0
          decay_min: 0
          output_min: experiment/environment/task/action_min++[0]
          output_max: experiment/environment/task/action_max++[0]
          projector: 
            type: projector/pre/normalizing
            input_min: experiment/environment/task/observation_min
            input_max: experiment/environment/task/observation_max
            projector: 
              type: projector/identity
          representation: 
            type: representation/parameterized/tensorflow
            interval: 10000
            inputs: experiment/environment/task/observation_dims
            targets: experiment/environment/task/action_dims
            file: ../cfg/network/4layer_tanh_ddpg.py experiment/environment/task/observation_dims experiment/environment/task/action_dims experiment/environment/task/action_max
            input_layer: s_in
            output_layer: a_out/mul, q/BiasAdd
            output_target: q_target
            update_node: q_update
    predictor: 
      type: predictor/ddpg
      gamma: 0.99
      observation: s_in
      action: a_in
      value: q/BiasAdd
      target: q_target
      critic_update: q_update
      actor_update: a_update
      obs_projector: 
        type: projector/pre/normalizing
        input_min: experiment/environment/task/observation_min
        input_max: experiment/environment/task/observation_max
        projector: 
          type: projector/identity
      action_projector: 
        type: projector/identity
      representation: experiment/agent/policy/policy/policy/representation
  test_agent: 
    type: agent/fixed
    policy: 
      type: mapping/policy/filtering
      observation_idx: [0, 1, 2, 3]
      action_idx: [0]
      policy: 
        type: mapping/policy/action
        sigma: 0
        decay_rate: 1
        decay_min: 0
        output_min: experiment/agent/policy/policy/policy/output_min
        output_max: experiment/agent/policy/policy/policy/output_max
        projector: experiment/agent/policy/policy/policy/projector
        representation: experiment/agent/policy/policy/policy/representation
  save_every: never
points: 4096
delay: 1
policy_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 0
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/policy/projector
    representation: experiment/agent/policy/policy/policy/representation
value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 1
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/policy/projector
    representation: experiment/agent/policy/policy/policy/representation
target_value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 1
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/policy/projector
    representation: experiment/agent/policy/policy/policy/representation/target
curve_visualization: 
  type: visualization/state
  input_dims: []
  input_min: [-4000]
  input_max: [0]
  memory: 256
  state: experiment/curve
